from . import events as _events


EVT_GL_OBJECT_SELECTED = _events.EVT_GL_OBJECT_SELECTED
EVT_GL_OBJECT_UNSELECTED = _events.EVT_GL_OBJECT_UNSELECTED
EVT_GL_OBJECT_ACTIVATED = _events.EVT_GL_OBJECT_ACTIVATED
EVT_GL_OBJECT_RIGHT_CLICK = _events.EVT_GL_OBJECT_RIGHT_CLICK
EVT_GL_OBJECT_RIGHT_DCLICK = _events.EVT_GL_OBJECT_RIGHT_DCLICK
EVT_GL_OBJECT_MIDDLE_CLICK = _events.EVT_GL_OBJECT_MIDDLE_CLICK
EVT_GL_OBJECT_MIDDLE_DCLICK = _events.EVT_GL_OBJECT_MIDDLE_DCLICK
EVT_GL_OBJECT_AUX1_CLICK = _events.EVT_GL_OBJECT_AUX1_CLICK
EVT_GL_OBJECT_AUX1_DCLICK = _events.EVT_GL_OBJECT_AUX1_DCLICK
EVT_GL_OBJECT_AUX2_CLICK = _events.EVT_GL_OBJECT_AUX2_CLICK
EVT_GL_OBJECT_AUX2_DCLICK = _events.EVT_GL_OBJECT_AUX2_DCLICK
EVT_GL_OBJECT_DRAG = _events.EVT_GL_OBJECT_DRAG
EVT_GL_LEFT_DOWN = _events.EVT_GL_LEFT_DOWN
EVT_GL_LEFT_UP = _events.EVT_GL_LEFT_UP
EVT_GL_LEFT_DCLICK = _events.EVT_GL_LEFT_DCLICK
EVT_GL_RIGHT_DOWN = _events.EVT_GL_RIGHT_DOWN
EVT_GL_RIGHT_UP = _events.EVT_GL_RIGHT_UP
EVT_GL_RIGHT_DCLICK = _events.EVT_GL_RIGHT_DCLICK
EVT_GL_MIDDLE_DOWN = _events.EVT_GL_MIDDLE_DOWN
EVT_GL_MIDDLE_UP = _events.EVT_GL_MIDDLE_UP
EVT_GL_MIDDLE_DCLICK = _events.EVT_GL_MIDDLE_DCLICK
EVT_GL_AUX1_DOWN = _events.EVT_GL_AUX1_DOWN
EVT_GL_AUX1_UP = _events.EVT_GL_AUX1_UP
EVT_GL_AUX1_DCLICK = _events.EVT_GL_AUX1_DCLICK
EVT_GL_AUX2_DOWN = _events.EVT_GL_AUX2_DOWN
EVT_GL_AUX2_UP = _events.EVT_GL_AUX2_UP
EVT_GL_AUX2_DCLICK = _events.EVT_GL_AUX2_DCLICK

GLEvent = _events.GLEvent
GLObjectEvent = _events.GLObjectEvent


del _events
