# © 2025-2026 Kevin G. Schlosser <kevin.g.schlosser@gmail.com>

from . import events as _events


EVT_GL_OBJECT_SELECTED = _events.EVT_GL_OBJECT_SELECTED
EVT_GL_OBJECT_UNSELECTED = _events.EVT_GL_OBJECT_UNSELECTED
EVT_GL_OBJECT_ACTIVATED = _events.EVT_GL_OBJECT_ACTIVATED
EVT_GL_OBJECT_RIGHT_CLICK = _events.EVT_GL_OBJECT_RIGHT_CLICK
EVT_GL_OBJECT_RIGHT_DCLICK = _events.EVT_GL_OBJECT_RIGHT_DCLICK
EVT_GL_OBJECT_MIDDLE_CLICK = _events.EVT_GL_OBJECT_MIDDLE_CLICK
EVT_GL_OBJECT_MIDDLE_DCLICK = _events.EVT_GL_OBJECT_MIDDLE_DCLICK
EVT_GL_OBJECT_AUX1_CLICK = _events.EVT_GL_OBJECT_AUX1_CLICK
EVT_GL_OBJECT_AUX1_DCLICK = _events.EVT_GL_OBJECT_AUX1_DCLICK
EVT_GL_OBJECT_AUX2_CLICK = _events.EVT_GL_OBJECT_AUX2_CLICK
EVT_GL_OBJECT_AUX2_DCLICK = _events.EVT_GL_OBJECT_AUX2_DCLICK
EVT_GL_OBJECT_DRAG = _events.EVT_GL_OBJECT_DRAG

EVT_GL_MOUSE_MOVE = _events.EVT_GL_MOUSE_MOVE
EVT_GL_LEFT_DOWN = _events.EVT_GL_LEFT_DOWN
EVT_GL_LEFT_UP = _events.EVT_GL_LEFT_UP
EVT_GL_LEFT_DCLICK = _events.EVT_GL_LEFT_DCLICK
EVT_GL_RIGHT_DOWN = _events.EVT_GL_RIGHT_DOWN
EVT_GL_RIGHT_UP = _events.EVT_GL_RIGHT_UP
EVT_GL_RIGHT_DCLICK = _events.EVT_GL_RIGHT_DCLICK
EVT_GL_MIDDLE_DOWN = _events.EVT_GL_MIDDLE_DOWN
EVT_GL_MIDDLE_UP = _events.EVT_GL_MIDDLE_UP
EVT_GL_MIDDLE_DCLICK = _events.EVT_GL_MIDDLE_DCLICK
EVT_GL_AUX1_DOWN = _events.EVT_GL_AUX1_DOWN
EVT_GL_AUX1_UP = _events.EVT_GL_AUX1_UP
EVT_GL_AUX1_DCLICK = _events.EVT_GL_AUX1_DCLICK
EVT_GL_AUX2_DOWN = _events.EVT_GL_AUX2_DOWN
EVT_GL_AUX2_UP = _events.EVT_GL_AUX2_UP
EVT_GL_AUX2_DCLICK = _events.EVT_GL_AUX2_DCLICK
EVT_GL_KEY_DOWN = _events.EVT_GL_KEY_DOWN
EVT_GL_KEY_UP = _events.EVT_GL_KEY_UP
EVT_GL_CAPTURE_LOST = _events.EVT_GL_CAPTURE_LOST

EVT_GL_CAMERA_ORBIT = _events.EVT_GL_CAMERA_ORBIT
EVT_GL_CAMERA_RESET = _events.EVT_GL_CAMERA_RESET
EVT_GL_CAMERA_ROTATE = _events.EVT_GL_CAMERA_ROTATE
EVT_GL_CAMERA_TRUCKPEDISTAL = _events.EVT_GL_CAMERA_TRUCKPEDISTAL
EVT_GL_CAMERA_WALK = _events.EVT_GL_CAMERA_WALK
EVT_GL_CAMERA_ZOOM = _events.EVT_GL_CAMERA_ZOOM


GLEvent = _events.GLEvent
GLObjectEvent = _events.GLObjectEvent
GLKeyEvent = _events.GLKeyEvent
GLCaptureLostEvent = _events.GLCaptureLostEvent
GLCameraEvent = _events.GLCameraEvent


del _events
