
print('import harness designer')
import harness_designer

harness_designer.__main__()

'''
CREATE TABLE boots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    part_number TEXT UNIQUE NOT NULL, 
    description TEXT DEFAULT "" NOT NULL, 
    mfg_id INTEGER DEFAULT 0 NOT NULL, 
    family_id INTEGER DEFAULT 0 NOT NULL, 
    series_id INTEGER DEFAULT 0 NOT NULL, 
    color_id INTEGER DEFAULT 0 NOT NULL, 
    material_id INTEGER DEFAULT 0 NOT NULL, 
    direction_id INTEGER DEFAULT 0 NOT NULL, 
    image_id INTEGER DEFAULT NULL, 
    datasheet_id INTEGER DEFAULT NULL, 
    cad_id INTEGER DEFAULT NULL, 
    min_temp_id INTEGER DEFAULT 0 NOT NULL, 
    max_temp_id INTEGER DEFAULT 0 NOT NULL, 
    model3d_id INTEGER DEFAULT NULL, 
    length REAL DEFAULT "0.0" NOT NULL, 
    width REAL DEFAULT "0.0" NOT NULL, 
    height REAL DEFAULT "0.0" NOT NULL, 
    weight REAL DEFAULT "0.0" NOT NULL, 
    compat_housings TEXT DEFAULT "[]" NOT NULL,
            FOREIGN KEY (mfg_id) REFERENCES manufacturers(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
    FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
        FOREIGN KEY (series_id) REFERENCES series(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
            FOREIGN KEY (color_id) REFERENCES colors(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
    FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
    FOREIGN KEY (direction_id) REFERENCES directions(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
    FOREIGN KEY (image_id) REFERENCES resources(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
    FOREIGN KEY (datasheet_id) REFERENCES resources(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
    FOREIGN KEY (cad_id) REFERENCES resources(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
    FOREIGN KEY (min_temp_id) REFERENCES temperatures(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
    FOREIGN KEY (max_temp_id) REFERENCES temperatures(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
    FOREIGN KEY (model3d_id) REFERENCES models3d(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
    
);


CREATE TABLE boots (id INTEGER PRIMARY KEY AUTOINCREMENT, part_number TEXT UNIQUE NOT NULL, description TEXT DEFAULT "" NOT NULL, mfg_id INTEGER DEFAULT 0 NOT NULL, FOREIGN KEY (mfg_id) REFERENCES manufacturers(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, family_id INTEGER DEFAULT 0 NOT NULL, FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, series_id INTEGER DEFAULT 0 NOT NULL, FOREIGN KEY (series_id) REFERENCES series(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, color_id INTEGER DEFAULT 0 NOT NULL, FOREIGN KEY (color_id) REFERENCES colors(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, material_id INTEGER DEFAULT 0 NOT NULL, FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, direction_id INTEGER DEFAULT 0 NOT NULL, FOREIGN KEY (direction_id) REFERENCES directions(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, image_id INTEGER DEFAULT NULL, FOREIGN KEY (image_id) REFERENCES resources(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, datasheet_id INTEGER DEFAULT NULL, FOREIGN KEY (datasheet_id) REFERENCES resources(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, cad_id INTEGER DEFAULT NULL, FOREIGN KEY (cad_id) REFERENCES resources(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, min_temp_id INTEGER DEFAULT 0 NOT NULL, FOREIGN KEY (min_temp_id) REFERENCES temperatures(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, max_temp_id INTEGER DEFAULT 0 NOT NULL, FOREIGN KEY (max_temp_id) REFERENCES temperatures(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, model3d_id INTEGER DEFAULT NULL, FOREIGN KEY (model3d_id) REFERENCES models3d(id) ON DELETE SET DEFAULT ON UPDATE CASCADE, length REAL DEFAULT "0.0" NOT NULL, width REAL DEFAULT "0.0" NOT NULL, height REAL DEFAULT "0.0" NOT NULL, weight REAL DEFAULT "0.0" NOT NULL, compat_housings TEXT DEFAULT "[]" NOT NULL);
'''