'''

HOUSINGS
----------------------------------------
{
    "features": [
        "Connector & Housing Type",
        "Performance Category",
        "Bus Bar Mount Orientation",
        "Operating Temperature (Max)",
        "Termination Method to PCB",
        "RF Connector Style",
        "Data Rate",
        "Nominal Voltage Architecture",
        "RF Connector Center Contact Material",
        "Conductor Combination 2",
        "Quick Disconnect Terminal Type",
        "Compatible Conductor Material",
        "Operating Temperature Range",
        "Mating Alignment Type",
        "Connector Contact Density",
        "Primary Locking Feature",
        "Bus Bar Connector Mounting Retention",
        "Card Edge Type",
        "Centerline (Pitch)",
        "Compatible With Agency/Standards Products",
        "EMI Containment Feature Type",
        "Shroud Style",
        "Internal I/O Connector Type",
        "Connector & Keying Code",
        "Data Transmission Mode",
        "PCB Connector Seating",
        "Connector Mounting Type",
        "Polarization Code",
        "PCB Thickness (Recommended)",
        "Piercing Blade Base Material",
        "RF Connector Mated Outer Diameter (Approximate)",
        "Bulkhead Style",
        "RF Contact Captivation Method",
        "Screw Flange",
        "Circular Connector Contact Type",
        "Contact Options",
        "Connector Contact Load Condition",
        "Palm Hole Diameter",
        "Lighting Connector Style",
        "Shielded",
        "Shell Material",
        "Multiple Port Configuration",
        "Number of Coaxial Contacts",
        "Mating Pin Diameter",
        "IP Rating",
        "Contact Mating Area Plating Material",
        "Mating & Unmating Configuration",
        "Rack & Panel Connector Shell Size",
        "Backplane Architecture",
        "Body Material Finish",
        "Fluid Resistance",
        "Detent",
        "Port Matrix Configuration",
        "Data Bus Connector Style",
        "Contacts Preloaded",
        "Mating Alignment",
        "Fiber Optic Mode",
        "Crimp Type",
        "Contact Base Material",
        "Alignment Keyed",
        "FPC Actuator Type",
        "Lighting Product Type",
        "Assembly Process Feature",
        "Number of Positions",
        "Number of Ports",
        "Impedance",
        "Circular DIN Connector Type",
        "PCB Mount Location",
        "Bus Bar Contact Plating Material",
        "Shell Type",
        "Number of Dual Positions",
        "Compatible Conductor Range - Main",
        "Modular Jack Latch Orientation",
        "PCB Connector Type",
        "Lighting Connector Type",
        "Panel Mount Feature",
        "USB Version",
        "Shield Plating Material",
        "Body Material",
        "PCB Mount Alignment",
        "Modular Connector Style",
        "Solar Connector Style",
        "T-Branch Style",
        "PCB Mount Orientation",
        "Assembly Length",
        "Number of Power Positions",
        "Contact Type",
        "Field Serviceable",
        "Sealable",
        "Connector Position Assurance Capable",
        "Contact Protection",
        "Connection Under Load (90A Max)",
        "Size Group",
        "Pluggable I/O Product Type",
        "Termination Method to Wire & Cable",
        "Contact Current Rating (Max)",
        "Contact Mating Retention",
        "Body Orientation",
        "Number of Columns",
        "FFC Connector Product Type",
        "PCB Mount Retention Type",
        "Number of Rows",
        "Product Installation Type",
        "Circular Connector Shell Size",
        "Body Plating Material",
        "Barrel Type",
        "Shell Plating Material",
        "Stackable",
        "Guide Location",
        "Connector Profile",
        "Industry Standard",
        "Header Type",
        "Insulation Option",
        "Packaging Method",
        "Grounding Options",
        "Contact Retention Within Housing",
        "Installation Technology",
        "Cable Type",
        "Row-to-Row Spacing",
        "Mating Retention",
        "Connector Height",
        "Connector Product Type",
        "Product Height",
        "Housing Color",
        "PCB Contact Termination Area Plating Material",
        "Insertion Force Type",
        "Compatible With Wire & Cable Type",
        "FFC Cable Entry",
        "Mating Conductor Thickness",
        "Port Configuration",
        "Number of Signal Positions",
        "RF Connector Coupling Mechanism",
        "Mating Cycles (Max)",
        "Compatible Conductor Range",
        "Dielectric Material",
        "Performance Level",
        "Reverse Gender",
        "Insertion Force",
        "Lighting Connector Features Included",
        "Mating Tab Width",
        "Mating Tab Thickness",
        "Bus Bar Mount Retention Type",
        "Terminal Orientation",
        "Soldering Temperature (Max)",
        "Terminal Plating Material",
        "Cable Exit Angle",
        "Compatible Cable Diameter Range",
        "Connector System",
        "Connector Mates With",
        "Form Factor",
        "Pigtail Length",
        "Circular Connector Shell Type",
        "Included Lightpipe",
        "Compatible Conductor Cross-Section Range - Tap",
        "Contact Length",
        "Operating Frequency Range",
        "Wire Size",
        "Circular Connector Type",
        "Compatible Conductor Cross-Section Range - Main",
        "Power Component Application Type",
        "Compatible With RF Cable Type",
        "Power Contact Centerline",
        "Circuit Application",
        "Operating Voltage",
        "Mating Entry Location",
        "Number of Loaded Positions",
        "Number of Holes",
        "Connector Shape",
        "UL Flammability Rating",
        "Contact Mating Location",
        "Terminal Type",
        "Stud Size",
        "Conductor Combination 1",
        "Shell Base Material",
        "EMI Finger Location",
        "Modular Jack & Plug Interface Type",
        "PCB Mount Retention",
        "RF Connector Center Contact Plating Material",
        "Data Rate (Max)",
        "Product Availability",
        "Voltage Class",
        "Termination Post & Tail Length",
        "Connector & Contact Terminates To",
        "RF Interface",
        "Solar Connector Type",
        "Panel Mount Feature Type",
        "Circular Connector Insulation Material Type",
        "Compression Connector Product Type",
        "Docking Connector Style",
        "Contact Mating Area Plating Material Thickness",
        "Modular Jacks & Plugs Products",
        "Connector Shell Size",
        "Primary Product Material",
        "Bus Bar Contact Style",
        "Hermetically Sealed",
        "Glow Wire Rating",
        "Housing Material",
        "Number of Utility Contacts",
        "Data Bus Connector Type",
        "Rows Loaded",
        "Primary Product Color",
        "USB Type",
        "Packaging Quantity",
        "Contact Layout Arrangement",
        "Compatible Conductor Cross-Section Range",
        "Palm Terminal Material",
        "Keying Type",
        "Mating Retention Type"
    ],
    "feature_groups": {
        "Product Type Features": [
            "Connector & Housing Type",
            "RF Connector Style",
            "Conductor Combination 2",
            "Card Edge Type",
            "Primary Locking Feature",
            "Integral Locking Latch",
            "Insulating Connector Product Type",
            "Shroud Style",
            "Internal I/O Connector Type",
            "Data Transmission Mode",
            "Compatible with PCB Type",
            "Piercing Blade Base Material",
            "Connector Seal & Plug Type",
            "Lighting Connector Style",
            "Terminal Features",
            "Prewired",
            "Rack & Panel Connector Shell Size",
            "Data Bus Connector Style",
            "Fiber Optic Mode",
            "Cage Type",
            "FPC Actuator Type",
            "Lighting Product Type",
            "Circular DIN Connector Type",
            "Shell Type",
            "PCB Connector Type",
            "Shell Material Configuration",
            "Signal Arrangement",
            "Eurocard Connector Configuration Type",
            "Lighting Connector Type",
            "USB Version",
            "Modular Connector Style",
            "Solar Connector Style",
            "Ground Feature Type",
            "Sealable",
            "Make First / Break Last Contacts Loaded",
            "Size Group",
            "Pluggable I/O Product Type",
            "FFC Connector Product Type",
            "Connector Mating Latch & Lock Type",
            "Fiber Optic Product Type",
            "Header Type",
            "Ribbon Cable Connector Type",
            "Installation Technology",
            "Grounding Options",
            "Connector Product Type",
            "Insertion Force Type",
            "Performance Level",
            "Applied Pressure",
            "Insertion Force",
            "Thermal Accessory Type Included",
            "Ribbon Cable Connector Header Type",
            "Backplane Interface Type",
            "Fiber Optic Cable Type",
            "Backplane Module Type",
            "Connector System",
            "Connector Mates With",
            "Form Factor",
            "Compatible With Discrete Wire Type",
            "Circular Connector Shell Type",
            "Mixed & Hybrid Header",
            "Assembly Requirement",
            "Circular Connector Type",
            "Compatible With RF Cable Type",
            "Power Component Options",
            "Connector Shape",
            "Assembly Type",
            "Stud Size",
            "Conductor Combination 1",
            "Modular Jack & Plug Interface Type",
            "Mixed & Hybrid Connector",
            "Connector & Contact Terminates To",
            "RF Interface",
            "Solar Connector Type",
            "Docking Connector Style",
            "Modular Jacks & Plugs Products",
            "Connector Shell Size",
            "Receptacle Configuration",
            "Data Bus Connector Type",
            "Product Line",
            "USB Type"
        ],
        "Configuration Features": [
            "Number of Bolts",
            "Lightpipe Style",
            "Connector Modification",
            "Number of Positions by Circuit Application",
            "Number of Positions",
            "Keying & Polarized Position Locations",
            "Number of Ports",
            "Connector Seal Code",
            "Number of Bays",
            "Number of Loaded Positions",
            "Number of Holes",
            "Number of Insulation Displacement Slots",
            "Number of Fins",
            "Number of Dual Positions",
            "Connector Contact Density",
            "Card Slot Centerline",
            "Factory Installed Backshell",
            "EMI Finger Location",
            "Endface Geometry",
            "Compatible With Wire & Cable Type",
            "Visual Inspection",
            "Port Configuration",
            "Reverse Numbering",
            "Stacking Configuration",
            "Number of Standoffs",
            "Number of PCB Ground Tabs",
            "Number of Signal Positions",
            "Wire Entry Location",
            "Board-to-Board Configuration",
            "Number of Ground Positions",
            "T-Branch Style",
            "Number of Panel Ground Tabs",
            "Number of Pairs",
            "PCB Mount Orientation",
            "Insertion Force",
            "Number of Inserts",
            "Release Style",
            "Keying & Polarized Rib Location",
            "Number of Power Positions",
            "Connector Contact Load Condition",
            "Lighting Connector Features Included",
            "Number of Mounting Legs",
            "Panel Ground Location",
            "Card Entry Style",
            "Number of Coax Positions",
            "Fuse Protection Level",
            "Number of Rear EONs per Port Column",
            "Multiple Port Configuration",
            "Number of Coaxial Contacts",
            "Power/Signal/Coax Combination",
            "Number of Power or Coaxial Positions",
            "Number of Sections",
            "PCB Retention Location",
            "Blank Cavity Position",
            "Keying Arrangement",
            "Mating & Unmating Configuration",
            "Rows Loaded",
            "Backplane Architecture",
            "Number of Columns",
            "Number of Cavities",
            "Number of Rows",
            "Pairs per Column",
            "Port Matrix Configuration",
            "Connection Capacity",
            "Contacts Preloaded",
            "Snap-Lock",
            "Stackable",
            "Keying Type",
            "Guide Location"
        ],
        "Contact Features": [
            "Contact Underplating Material Thickness",
            "Contact Quantity (Size 12)",
            "Feedthrough Post Length",
            "Contact Arrangement Code (Module E)",
            "RF Connector Center Contact Material",
            "Quick Disconnect Terminal Type",
            "Contact Type (Module C)",
            "Ferrule Material",
            "Contact Arrangement Code",
            "Contact Quantity (Size 12 Databus)",
            "Contact Mating Area Length",
            "Contact Arrangement Code (Module C)",
            "Cavity 3 Blade Length",
            "Multiple Contact Types",
            "Circular Connector Contact Type",
            "Contact Options",
            "Contact Plating Material",
            "Contact Arrangement Code (Module A)",
            "Mating Pin Diameter",
            "Cavity 1 Blade Length",
            "Center Contact",
            "Contact Mating Area Plating Material",
            "Power Contact Base Material",
            "Contact Arrangement Code (Module D)",
            "Crimp Type",
            "Contact Base Material",
            "Wire Contact Termination Area Plating Material Finish",
            "Signal Contact Material",
            "Contact Shape & Form",
            "Contact Quantity (Size 12 Coax)",
            "Contact Fabrication",
            "Wire Contact Termination Area Plating Material",
            "Contact Type (Module D)",
            "Contact Type",
            "Rack & Panel Connector Contact Style",
            "Contact Size",
            "CompactPCI Designation",
            "Contact Protection",
            "Contact Quantity (Size 16)",
            "Mating Square Post Dimension",
            "Contact Quantity (Size 22D)",
            "Contact Current Rating (Max)",
            "Contact Mating Retention",
            "RF Connector Center Contact Underplating Material",
            "Barrel Type",
            "PCB Contact Termination Area Plating Material Finish",
            "Contact Protection Type",
            "Tail Plating Material",
            "Contact Retention Within Housing",
            "PCB Contact Termination Area Plating Material",
            "PCB Contact Termination Area Plating Material Thickness",
            "Wire Contact Termination Area Plating Thickness",
            "Contact Underplating Material",
            "Reverse Gender",
            "Contact Type (Module B)",
            "Mating Tab Width",
            "Mating Tab Thickness",
            "Terminal Orientation",
            "Terminal Plating Material",
            "RF Connector Contact Configuration",
            "Contact Length",
            "Contact Type (Module A)",
            "Contact Mating Area Plating Material Finish",
            "Contact Quantity (Size 20)",
            "Contact Quantity (Size 12 Shielded)",
            "Terminal Type",
            "Contact Mating Location",
            "PCB Termination Area Plating Finish",
            "Cavity 4 Blade Length",
            "RF Connector Center Contact Plating Thickness",
            "RF Connector Center Contact Plating Material",
            "Outer Contact Plating Material",
            "Contact Arrangement Code (Module B)",
            "Contact Arrangement Code (Module F)",
            "Contact Layout",
            "Power Contact Plating Material",
            "Contact Quantity (Size 8 Databus)",
            "Contact Mating Area Plating Material Thickness",
            "Ferrule Plating Material",
            "Bus Bar Contact Style",
            "Number of Utility Contacts",
            "Contact Layout Arrangement",
            "Cavity 2 Blade Length",
            "Signal Contact Plating Material"
        ],
        "Mechanical Attachment": [
            "Detent Type",
            "Contact Retention Type Within Housing",
            "Mounting Feature Material",
            "Bus Bar Mount Orientation",
            "Connector Hardware Type",
            "PCB Mount Location",
            "Mating Retention",
            "Mating Alignment Type",
            "Mounting Holes",
            "Bus Bar Connector Mounting Retention",
            "Mechanical Reinforcement",
            "Terminal Position Assurance",
            "PCB Mount Retention",
            "Panel Mount Feature",
            "PCB Connector Seating",
            "Connector Mounting Type",
            "Extraction Force",
            "PCB Mounting Style",
            "Clinch Nut Quantity",
            "Polarization Code",
            "RF Connector Coupling Mechanism",
            "PCB Mount Alignment",
            "RF Contact Captivation Method",
            "Strain Relief",
            "Thread Size",
            "Panel Mount Feature Type",
            "Locking Feature",
            "Screw Flange",
            "Clinch Nut Size",
            "Guide Hardware",
            "Bus Bar Mount Retention Type",
            "Mounting Feature Plating Material",
            "PCB Mount Alignment Type",
            "Locking Lance Height",
            "Panel Attachment Style",
            "Shear Head Breaking Torque",
            "Mounting Hole Diameter",
            "PCB Mount Retention Type",
            "Detent",
            "Front Mating Level",
            "Assembly Process Feature Plating Material",
            "Mating Retention Feature Plating Material",
            "Mounting Hardware",
            "Mating Alignment",
            "Mounting Alignment Feature Length",
            "Locking Latch Between Cavity Number",
            "Mating Retention Type",
            "Wire Insulation Support"
        ],
        "Housing Features": [
            "Housing Color",
            "Wire & Cable IDC Installation Type",
            "Right Angle Bending Side",
            "Centerline (Pitch)",
            "Housing Material",
            "FFC Cable Entry",
            "Body Orientation",
            "Mating Entry Location",
            "End Wall Location",
            "Shell Material",
            "Circular Connector Shell Size",
            "Cage Material",
            "Housing Entry Configuration",
            "Number of Shrouded Sides",
            "Housing Plating Material",
            "Alignment Keyed"
        ],
        "Dimensions": [
            "Compatible Conductor Range - Tap (AAC)",
            "Compatible Conductor Cross-Section Range - Main",
            "Power Contact Centerline",
            "Compatible Conductor Range - Main (Copper)",
            "Profile Height from PCB",
            "Connector Length",
            "Compatible Conductor Range - Tap",
            "Terminal Material Thickness",
            "Lug Length",
            "Shrouded End Dimension",
            "Product Length",
            "Compatible Conductor Range - Tap (Copper)",
            "Row-to-Row Spacing",
            "Connector Height",
            "Product Height",
            "Connector Width",
            "Cable Diameter Range",
            "Compatible Conductor Range - Main",
            "Compatible Conductor Cross-Section Range - Main (Copper)",
            "Card Slot Depth",
            "Compatible Insulation Diameter (Max)",
            "Accepts Flex Cable Thickness",
            "Stack Height",
            "PCB Hole Diameter",
            "Accepts Card Width",
            "Compatible Conductor Cross-Section Range - Tap (Copper)",
            "Solid Wire Size",
            "Conductor Insulation Diameter Range",
            "Barrel Outside Diameter",
            "Post-Mating Assembly Measurement",
            "PCB Thickness (Recommended)",
            "Panel Thickness (Recommended)",
            "Lug Width",
            "RF Connector Mated Outer Diameter (Approximate)",
            "Compatible Conductor Range",
            "Compatible With Wire Insulation Thickness (Max)",
            "Barrel Length",
            "Assembly Length",
            "PCB Thickness (Min)",
            "Product Diameter",
            "Palm Hole Diameter",
            "Accepts Card Thickness",
            "Mounting Post Length",
            "Compatible Conductor Range - Tap (ACSR)",
            "Stranded Wire Size",
            "Compatible Cable Diameter Range",
            "Shear Head Size (Across Flats)",
            "Compatible Conductor Range - Main (ACSR)",
            "Compatible Fiber Diameter",
            "Compatible Cable Insulation Diameter Range",
            "Compatible Cable Diameter (Max)",
            "Pigtail Length",
            "Compatible Conductor Range - Main (AAC)",
            "Barrel Inside Diameter",
            "Product Width",
            "Compatible Insulation Diameter Range",
            "Compatible Conductor Cross-Section Range",
            "Compatible Conductor Cross-Section Range - Tap",
            "Boot Length",
            "Wire Size"
        ],
        "Usage Conditions": [
            "Insulation Option",
            "Operating Temperature (Max)",
            "IP Dust Sealing Level",
            "Fluid Resistance",
            "IP Water Sealing Level",
            "Housing Temperature Rating",
            "Soldering Temperature (Max)",
            "Installation Temperature Range",
            "Mating Cycles (Max)",
            "Cable Type",
            "Operating Temperature Range"
        ],
        "Operation/Application": [
            "Compression Connector Product Type",
            "Power Component Application Type",
            "Assembly Process Feature",
            "Durability Rating",
            "Circuit Application",
            "Compatible With Wire Base Material",
            "Heat Sink Compatible",
            "Power Component Connection Type",
            "Solder Process Feature",
            "Shielded",
            "Halogen Free",
            "Solder Process",
            "Conforms to Automation Guideline",
            "Indicator Type",
            "Pluggable I/O Applications",
            "Operating Frequency Range"
        ],
        "Electrical Characteristics": [
            "Voltage Rating",
            "Insulation Resistance",
            "Dielectric Withstanding Voltage (Max)",
            "Operating Voltage",
            "Impedance",
            "Termination Resistance",
            "Voltage Class",
            "Data Rate (Max)",
            "Operating Voltage (Max)",
            "Voltage Rating (Max)",
            "Contact Resistance",
            "Connection Under Load (90A Max)",
            "Nominal Voltage Architecture",
            "Current Rating",
            "EMI & RFI Protection & Suppression Type"
        ],
        "Body Features": [
            "Compression Barrel Type",
            "Body Underplating Material",
            "Compatible Conductor Material",
            "Front Shell Material",
            "Connector & Keying Code",
            "Cage Plating Material",
            "Connector Seal Color",
            "LED Color (Top Right)",
            "Environmental Protection",
            "Bulkhead Style",
            "Front Shell Plating Material",
            "Panel Ground Feature Type",
            "Environmental Protection Type",
            "Heat Sink Height",
            "Protective Cap Material",
            "Rear Shell Material",
            "Body Material Finish",
            "Guide Pin Style",
            "Seal Material",
            "Positive Stop Ferrule",
            "Heat Sink Style",
            "Bus Bar Contact Plating Material",
            "Ferrule Underplating Material",
            "Mating Feature Plating Material",
            "Modular Jack Latch Orientation",
            "Insert Material",
            "Mating Retention Feature Material",
            "Keying Between Cavity Locations",
            "Shield Plating Material",
            "Seal Type",
            "Body Material",
            "Mating Alignment Feature Material",
            "Grounding Tab Plating Material",
            "Primary Product Plating Material",
            "Boot Type",
            "Rear Shell Plating Material",
            "Cable Exit Type",
            "Flying Leads Length",
            "Conductor Type",
            "D-Sub Connector Insert Arrangement",
            "PCB Retention Feature Material",
            "Product Weight",
            "Ground Plate Material",
            "Body Plating Material",
            "Shell Plating Material",
            "Conductor Type (Small)",
            "Heat Sink Height Class",
            "Shield Plating Thickness",
            "Ribbon Cable Centerline Spacing",
            "Connector Profile",
            "Backshell Plating Material",
            "Assembly Process Feature Material",
            "Ground Plate Plating Material",
            "Product Orientation",
            "Strain Relief Type",
            "Ferrule",
            "Actuator Color",
            "Boot Color",
            "Shield Plating Finish",
            "Offset",
            "Header Mating Direction",
            "Cable Color",
            "Cable Exit Angle",
            "Conductor Type (Large)",
            "Feedthrough Type",
            "LED Color (Bottom Right)",
            "Insulation Material",
            "Wire Stuffer Cap Color",
            "Shell Plating Finish",
            "Insulation Color",
            "Fluid Type",
            "LED Color (Bottom Left)",
            "Daisy Chain",
            "Spring Plating Material",
            "Heat Sink Finish",
            "Mating Feature Material",
            "LED Color (Top Left)",
            "Entry Style",
            "PCB Ground Tab Location",
            "Shell Base Material",
            "Wire Color (Base)",
            "O-Ring Material",
            "Peripheral Seal Material",
            "PCB Retention Feature Plating Material",
            "Insulator Material",
            "Cover Material",
            "Circular Connector Insulation Material Type",
            "Shell Finish",
            "Primary Product Material",
            "Hermetically Sealed",
            "Shield Rating",
            "Shield Material",
            "Primary Product Color",
            "Flexibility",
            "Palm Terminal Material"
        ],
        "Termination Features": [
            "Termination Method to Wire & Cable",
            "Termination Cover",
            "Rectangular Termination Post & Tail Thickness",
            "Termination Cover Type",
            "Termination Method to PCB",
            "Rectangular Termination Post & Tail Width",
            "Square Termination Post & Tail Dimension",
            "Termination Post & Tail Length",
            "Terminations per Post (Max)",
            "Termination Cover Method",
            "Product Terminates To",
            "Termination Post & Tail Diameter"
        ],
        "Industry Standards": [
            "Industry Standard",
            "RAST Version",
            "Glow Wire Rating",
            "Compatible With Agency/Standards Products",
            "Performance Category",
            "Compatible With Approved Standards Products",
            "NEMA Spacing (2-Hole)",
            "Glow Wire Material Rating",
            "Test Identification (TID)",
            "UL Rating",
            "UL Flammability Rating",
            "CSA Rating",
            "Moisture Sensitivity Level",
            "IP Rating"
        ],
        "Packaging Features": [
            "Packaging Reel Diameter",
            "Packaging Method",
            "Packaging Quantity"
        ],
        "Signal Characteristics": [
            "Crosstalk Version",
            "Data Rate",
            "Number of Differential Pairs per Column",
            "Differential Impedance",
            "Differential Signaling"
        ],
        "Other": [
            "Grade",
            "Number of Blocked Positions",
            "Barrel Color",
            "Spring Material",
            "Coupling Nut Plating Material",
            "Gasket Material",
            "Serviceable",
            "EMI Containment Feature Type",
            "Mating Conductor Thickness",
            "Military Category",
            "Number of Panel Mounting Holes",
            "Lockwasher Material",
            "Shield Panel Ground Type",
            "Additional Features",
            "Dielectric Material",
            "Coupling Nut Base Material",
            "Ground Rod Material Type",
            "Coupling Nut Plating Finish",
            "Field Serviceable",
            "Connector Position Assurance Capable",
            "Color Cartridge Required",
            "Position Locations Omitted",
            "Die Color Code",
            "Custom Order Code",
            "Line",
            "Number of High Speed Data Positions",
            "Product Installation Type",
            "Included Lightpipe",
            "Interface Number",
            "Cable Assembly Length Range"
        ],
        "Product Availability": [
            "Product Availability"
        ],
        "Identification Marking": [
            "Circuit Identification Feature"
        ]
    },
    "base_categories": [
        "Energy & Power",
        "Automotive Parts",
        "Fiber Optics",
        "Cable Assemblies",
        "Terminals & Splices",
        "Connectors"
    ],
    "parent_categories": [
        "Industrial Mini I/O Connectors",
        "Data Connectivity Headers",
        "RJ45 Connectors",
        "RJ22 Connectors",
        "PC/104 Connectors",
        "Ballast Connectors",
        "Street Lighting Receptacles",
        "Backplane Connector Housings",
        "Insulation Piercing Connectors",
        "RJ11 Connectors",
        "SC Connectors",
        "Compression Connectors",
        "Plug & Socket Lighting Connectors",
        "Board-In Connectors",
        "MC801 Fiber Connectors",
        "Poke-In Connectors",
        "Card Edge Power Connectors",
        "Data Connectivity Housings",
        "Solar Connectors",
        "PCB Headers & Receptacles",
        "Crimp Terminal Housings",
        "DIN Connectors",
        "Coax Connectors",
        "Docking Connectors",
        "Ribbon Cable Connectors",
        "RJ14 Connectors",
        "Expanded Beam Fiber Housings",
        "USB Connectors",
        "Two-Piece Edge Connectors",
        "High Speed Backplane Connectors",
        "Grounding/Earthing Connectors",
        "LC Connectors",
        "HSSDC2 Connectors",
        "Eurocard Connectors",
        "Card Edge Connector Housings",
        "RJ25 Connectors",
        "Busbar Connectors",
        "DisplayPort Connectors",
        "High Speed Pluggable IO Connectors & Cages",
        "Quick Disconnects",
        "Standard Rectangular Connectors",
        "RJ Point Five Connectors",
        "IEEE 1394 Connectors",
        "FFC Connectors",
        "Automotive Headers",
        "Hard Metric Backplane Connectors",
        "Wedge Connectors",
        "Rack & Panel Connectors",
        "DC Jack Connectors",
        "Street Lighting Connectors",
        "D-Shaped Connectors",
        "Standard Edge Connectors",
        "Automotive Housings",
        "Circular Power Connectors",
        "HDMI Connectors",
        "Internal I/O Connectors",
        "SDL Connectors",
        "FPC Connectors",
        "Backplane Power Connectors",
        "Data Bus Connectors",
        "Insulating Connectors",
        "Standard Circular Connectors"
    ],
    "brands": [
        "TE Connectivity",
        "POLAMCO",
        "AMP",
        "Transpower",
        "Nanonics",
        "Raychem",
        "ERNI",
        "Crompton Instruments",
        "Microdot",
        "DEUTSCH",
        "Schrack",
        "Buchanan",
        "Elcon",
        "Greenpar",
        "HTS",
        "Simel"
    ]
}


'''