'''


TERMINALS
----------------------------------------
{
    "features": [
        "Magnet Wire Terminal Type",
        "Ring Terminal Product Type",
        "Operating Temperature (Max)",
        "Profile Height from PCB",
        "Termination Method to PCB",
        "Cable Shield Style",
        "Crimp Area Length",
        "Rectangular Connector Insert Type",
        "Nominal Voltage Architecture",
        "Operating Temperature Range",
        "Primary Locking Feature",
        "Compatible Insulation Diameter (Max)",
        "Centerline (Pitch)",
        "PCB Hole Diameter",
        "Connector Mounting Type",
        "Compatible With Wire Plating Material",
        "PCB Thickness (Recommended)",
        "Foil Terminal Body Type",
        "Tongue Thickness",
        "Mating Pin Diameter",
        "Contact Mating Area Plating Material",
        "Barrel Inside Diameter",
        "Terminal Profile",
        "Length (Installed)",
        "Product Terminates To",
        "Contact Base Material",
        "Number of Positions",
        "Contact Fabrication",
        "Wire Contact Termination Area Plating Material",
        "Armoring Material",
        "Tab Length",
        "Wire Insulation Support Retention Type",
        "Special Purpose Terminal Type",
        "Compatible Cable Cross-Section Range",
        "PCB Mount Orientation",
        "Contact Type",
        "Contact Size",
        "Sealable",
        "Number of Sheds",
        "Termination Method to Wire & Cable",
        "Terminal Seal Type",
        "Contact Current Rating (Max)",
        "Terminal Size",
        "Barrel Type",
        "Compatible Insulation Diameter Range",
        "Lead Wire Size",
        "Circular Connector Insert Type",
        "Accepts Foil Thickness (Max)",
        "Wire Size Search",
        "Wire Insulation Support",
        "Stock Thickness (Magnet Wire Side)",
        "Compatible With Wire Base Material",
        "Insulation Option",
        "Terminal Material Thickness",
        "Sheath Outside Diameter",
        "Aluminum Wire Size",
        "Installation Technology",
        "Packaging Method",
        "Contact Retention Within Housing",
        "Product Length",
        "PCB Contact Termination Area Plating Material",
        "Compatible With Wire & Cable Type",
        "PCB Contact Termination Area Plating Material Thickness",
        "Terminal Transmits",
        "Contact Underplating Material",
        "Vibration Class Level",
        "Conductor Shape",
        "Compatible Conductor Range",
        "Power Terminal Type",
        "Termination Length",
        "Mating Tab Width",
        "Mating Tab Thickness",
        "Fiber Optic Cable Type",
        "Compatible With Cavity Size",
        "Terminal Orientation",
        "Terminal Plating Material",
        "Connector System",
        "Pole Configuration",
        "Insulation Material",
        "Compatible With Discrete Wire Type",
        "Foil Terminal Type",
        "Compatible Conductor Cross-Section Range - Branch",
        "Wire Size",
        "Compatible Conductor Cross-Section Range - Main",
        "Power Component Options",
        "Contact Retention Type Within Housing",
        "Circuit Application",
        "Operating Voltage",
        "Magnet Wire Size",
        "Terminal Type",
        "Stud Size",
        "PCB Terminal Type",
        "Product Availability",
        "Voltage Class",
        "Connector & Contact Terminates To",
        "Installation Instruction",
        "Contact Mating Area Plating Material Thickness",
        "Number of Cores",
        "Interface Plating",
        "Spade Terminal Type",
        "Compatible Conductor Diameter Range",
        "Shed Inside Diameter",
        "Stud Diameter",
        "Cable Termination Tail Length",
        "Mating Retention Type"
    ],
    "feature_groups": {
        "Product Type Features": [
            "Ring Terminal Product Type",
            "Rectangular Connector Insert Type",
            "Primary Locking Feature",
            "Insertion Force",
            "Power Terminal Type",
            "Sealable",
            "Connector System",
        ],
        "Electrical Characteristics": [
            "Voltage Rating",
            "Operating Voltage",
            "Contact Resistance",
            "Current Rating",
        ],
        "Contact Features": [
            "Magnet Wire Terminal Type",
            "Contact Retention Within Housing",
            "Terminal Type",
            "Contact Diameter",
            "Special Purpose Terminal Type",
            "Contact Type",
            "Mating Tab Width",
            "Terminal Orientation",
            "Terminal Plating Material",
            "Mating Pin Diameter",
            "Contact Mating Area Plating Material",
            "Spade Terminal Type",
            "Contact Current Rating (Max)",
            "Barrel Type",
            "Typical Current Rating",
            "Contact Base Material"
        ],
        "Mechanical Attachment": [
            "Contact Retention Type Within Housing",
            "Mating Retention Type",
        ],
        "Dimensions": [
            "Compatible Conductor Cross-Section Range - Main",
            "Sheath Outside Diameter",
            "Aluminum Wire Size",
            "Magnet Wire Size",
            "Product Length",
            "Compatible Insulation Diameter (Max)",
            "Terminal Height",
            "Compatible Insulation Diameter (Min)",
            "Aluminum Magnet Wire Size",
            "Aluminum Lead Wire Size",
            "Compatible Cable Cross-Section Range",
            "Compatible Conductor Range",
            "Copper Magnet Wire Size",
            "Copper Lead Wire Size",
            "Accepts Conductor Width",
            "Compatible Cable Diameter Range",
            "Compatible Fiber Diameter",
            "Compatible Conductor Diameter Range",
            "Shed Inside Diameter",
            "Barrel Inside Diameter",
            "Compatible Insulation Diameter Range",
            "Lead Wire Size",
            "Length (Installed)",
            "Compatible Conductor Cross-Section Range - Branch",
            "Wire Size"
        ],
        "Usage Conditions": [
            "Operating Temperature Range"
        ],
        "Configuration Features": [
            "Number of Positions",
            "Connection Capacity",
        ],
        "Body Features": [
            "Seal Type",
            "Insulation Sleeve Color",
            "Terminal & Contact Weight",
            "Compatible With Cavity Size",
            "Primary Product Material",
            "Stripe Color",
            "Protective Cap Material",
            "Terminal Seal Type",
            "Insulation Material",
            "Primary Product Color",
            "Terminal Profile",
            "Circular Connector Insert Type"
        ],
    },
    "base_categories": [
        "Energy & Power",
        "Automotive Parts",
        "Fiber Optics",
        "Terminals & Splices",
        "Connectors",
        "Wire Protection & Management"
    ],
    "parent_categories": [
        "Special Purpose Terminals",
        "Shielded Contacts",
        "PCB Terminals",
        "Automotive Terminals",
        "Ring Connectors",
        "Spade Terminals",
        "Connector Contacts",
        "Power Cable Terminations",
        "Foil Terminals",
        "Busbars & Terminals",
        "Circular Connector Contact Inserts",
        "Magnet Wire Terminals",
        "Junction Contacts",
        "Fiber Optic Termini",
        "Rectangular Contact Inserts",
        "Ring Terminals",
        "Power Terminals"
    ],
    "brands": [
        "TE Connectivity",
        "AMP",
        "Transpower",
        "Raychem",
        "ERNI",
        "DEUTSCH",
        "Hellstern",
        "Elcon",
        "HTS",
        "Simel"
    ]
}

'''