# © 2025-2026 Kevin G. Schlosser <kevin.g.schlosser@gmail.com>

"""Abstract base classes for database connector implementations."""

from typing import Optional as _Optional, Generator as _Generator
from . import db_data as _db_data


class ConnectorBase:

    """Define the abstract interface shared by database connectors.
    """
    def __init__(self, mainframe, db_name):
        """Initialize shared connector state.

        :param mainframe: Main application frame that owns the connector.
        :type mainframe: UNKNOWN
        :param db_name: Database name or path managed by the connector.
        :type db_name: UNKNOWN
        """
        self.mainframe = mainframe
        self.db_name = db_name
        self._db_data = None

    # @property
    # def db_data(self):
    #     """Return the lazily created database seed-data helper.
    #
    #     :returns: Return value for this callable. UNKNOWN.
    #     :rtype: UNKNOWN
    #     """
    #     if self._db_data is None:
    #         self._db_data = _db_data.DBData()
    #
    #     return self._db_data

    # @db_data.setter
    # def db_data(self, value):
    #     """Clear and close the cached seed-data helper when set to ``None``.
    #
    #     :param value: Value or state to persist.
    #     :type value: UNKNOWN
    #     """
    #     if value is None:
    #         if self._db_data is not None:
    #             self._db_data.close()
    #             self._db_data = None

    def get_tables(self) -> list[str]:
        """Return the table names available through the connector.

        :returns: A list of table names.
        :rtype: list[str]
        :raises NotImplementedError: Raised by the abstract base implementation.
        """
        raise NotImplementedError

    def connect(self, splash) -> bool:
        """Establish the underlying database connection.

        :returns: ``True`` when the connection succeeds; otherwise ``False``.
        :rtype: bool
        :raises NotImplementedError: Raised by the abstract base implementation.
        """
        raise NotImplementedError

    def execute(self, operation: str,
                params: _Optional[tuple] = None,
                multi: bool = False) -> _Optional[_Generator]:
        """Execute a single database operation.

        :param operation: SQL statement to execute.
        :type operation: str
        :param params: Parameters supplied for the SQL operation.
        :type params: _Optional[tuple]
        :param multi: Whether the connector should execute multiple statements.
        :type multi: bool

        :returns: The connector-specific cursor result, if one is returned.
        :rtype: UNKNOWN
        :raises NotImplementedError: Raised by the abstract base implementation.
        """
        raise NotImplementedError

    def executemany(self, operation: str,
                    seq_params: list | tuple) -> _Optional[_Generator]:
        """Execute a database operation for multiple parameter sets.

        :param operation: SQL statement to execute.
        :type operation: str
        :param seq_params: Sequence of parameter sets to execute.
        :type seq_params: list | tuple

        :returns: The connector-specific cursor result, if one is returned.
        :rtype: UNKNOWN
        :raises NotImplementedError: Raised by the abstract base implementation.
        """
        raise NotImplementedError

    @property
    def lastrowid(self) -> _Optional[int]:
        """Return the identifier generated by the last insert operation.

        :returns: The row identifier reported by the active cursor.
        :rtype: int | None
        :raises NotImplementedError: Raised by the abstract base implementation.
        """
        raise NotImplementedError

    def fetchone(self) -> _Optional[list[tuple]]:
        """Fetch a single row from the active cursor.

        :returns: The next row from the cursor, if available.
        :rtype: UNKNOWN
        :raises NotImplementedError: Raised by the abstract base implementation.
        """
        raise NotImplementedError

    def fetchmany(self, size: _Optional[int] = None) -> list[tuple]:
        """Fetch multiple rows from the active cursor.

        :param size: Maximum number of rows to fetch.
        :type size: _Optional[int]

        :returns: A list of fetched rows.
        :rtype: list[tuple]
        :raises NotImplementedError: Raised by the abstract base implementation.
        """
        raise NotImplementedError

    def fetchall(self) -> list[tuple]:
        """Fetch all remaining rows from the active cursor.

        :returns: All remaining rows from the cursor.
        :rtype: list[tuple]
        :raises NotImplementedError: Raised by the abstract base implementation.
        """
        raise NotImplementedError

    def commit(self) -> None:
        """Commit the current database transaction.

        :returns: ``None``.
        :rtype: None
        :raises NotImplementedError: Raised by the abstract base implementation.
        """
        raise NotImplementedError

    def close(self) -> None:
        """Close the connector and release any open resources.

        :returns: ``None``.
        :rtype: None
        :raises NotImplementedError: Raised by the abstract base implementation.
        """
        raise NotImplementedError
