
MODULE_NAMES = '''\
ipython_pygments_lexers
trianglesolver
typing_extensions
decorator
six
pyassimp
harness_designer
lib3mf
pyassimp
OpenGL_accelerate
OpenGL
pymupdf
wx
mysql
numpy
PIL
pyparsing
packaging
kiwisolver
fontTools
cycler
svgelements
cadquery_ocp_proxy
mpmath
webcolors
isodate
lark
mdurl
pygments
traitlets
pure_eval
asttokens
executing
wcwidth
parso
colorama
anytree
ezdxf
jedi
matplotlib_inline
prompt_toolkit
stack_data
contourpy
scipy
sympy
shapely
markdown_it
cv2
pyfqmr
dateutil
ocp_gordon
rich
requests
meshio
ifcopenshell
svgwrite
svgpathtools
IPython
matplotlib
vtk
vtkmodules
cadquery_ocp
ocpsvg
build123d'''


def get_modules():
    res = []
    for name in MODULE_NAMES.split('\n'):
        mod = __import__(name)
        if mod.__file__ is None:
            cmd = [f'--hidden-import={name}']
        elif '__init__' in mod.__file__:
            cmd = [f'--collect-all={name}']
        else:
            cmd = [f'--hidden-import={name}']

        res.extend(cmd)

    return res


'''
curses
OpenGL.raw.GLES3
OpenGL\Tk\togl-win32-64
wx.lib.pubsub
wx.lib.pubsub.core.kwargs
mysql.ai.ml
numpy.f2py.tests
pyparsing.diagram
ezdxf.addons.browser
prompt_toolkit.contrib.ssh
scipy._lib.array_api_compat.torch
networkx
matplotlib.tests
ctypes.test
distutils._log
distutils._macos_compat
distutils._modified
distutils.command._framework_compat
distutils.compat
distutils.compat.numpy
distutils.compat.py39
distutils.tests
distutils.zosccompiler
idlelib.idle_test
lib2to3.tests
tkinter.test
wx.lib.pubsub.core.datamsg
numpy.fft.tests
numpy.ma.tests
numpy.linalg.tests
numpy.lib.tests
numpy.matrixlib.tests
numpy.polynomial.tests
numpy.random.tests
numpy.tests
mpmath.tests
traitlets.tests
colorama.tests
scipy._lib.tests
scipy.cluster.tests
scipy.constants.tests
scipy.differentiate.tests
scipy.fft.tests
scipy.fftpack.tests
scipy.integrate._ivp.tests
scipy.integrate.tests
scipy.interpolate.tests
scipy.io._harwell_boeing.tests
scipy.io.arff.tests
scipy.io.matlab.tests
scipy.io.tests
scipy.linalg.tests
scipy.ndimage.tests
scipy.odr.tests
scipy.optimize.tests
scipy.signal.tests
scipy.sparse.csgraph.tests
scipy.sparse.linalg._isolve.tests
scipy.sparse.linalg._eigen.tests
scipy.sparse.tests
scipy.spatial.tests
scipy.special.tests
scipy.stats.tests
sympy.algebras.tests
sympy.assumptions.tests
sympy.calculus.tests
sympy.categories.tests
sympy.codegen.tests
sympy.combinatorics.tests
sympy.concrete.tests
sympy.core.tests
sympy.crypto.tests
sympy.diffgeom.tests
sympy.discrete.tests
sympy.external.tests
sympy.functions.combinatorial.tests
sympy.functions.elementary.tests
sympy.functions.special.tests
sympy.geometry.tests
sympy.holonomic.tests
sympy.integrals.tests
sympy.interactive.tests
sympy.liealgebras.tests
sympy.logic.tests
sympy.matrices.expressions.tests
sympy.matrices.tests
sympy.multipledispatch.tests
sympy.ntheory.tests
sympy.parsing.tests
sympy.physics.biomechanics.tests
sympy.physics.continuum_mechanics.tests
sympy.physics.control.tests
sympy.physics.hep.tests
sympy.physics.mechanics.tests
sympy.physics.optics.tests
sympy.physics.quantum.tests
sympy.physics.tests
sympy.physics.units.tests
sympy.physics.vector.tests
sympy.plotting.intervalmath.tests
sympy.plotting.pygletplot.tests
sympy.plotting.tests
sympy.polys.agca.tests
sympy.polys.domains.tests
sympy.polys.matrices.tests
sympy.polys.numberfields.tests
sympy.polys.tests
sympy.printing.tests
sympy.sandbox.tests
sympy.series.tests
sympy.sets.tests
sympy.simplify.tests
sympy.solvers.ode.tests
sympy.solvers.tests
sympy.stats.sampling.tests
sympy.stats.tests
sympy.strategies.branch.tests
sympy.strategies.tests
sympy.tensor.array.expressions.tests
sympy.tensor.array.tests
sympy.tensor.tests
sympy.testing.tests
sympy.unify.tests
sympy.utilities.tests
sympy.vector.tests
shapely.tests
vtkmodules.test
vtkmodules.util.data_model
vtkmodules.util.execution_model
vtkmodules.vtkRenderingVRModels
scipy.special._cdflib
sequence.recalculate_schedule

'''